/**
 * Cities Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CitiesApiResponseMessage } from './cities-api-response-message';
import { CitiesResponseData } from './cities-response-data';


export interface CitiesApiResponse { 
    success: boolean;
    data: CitiesResponseData | null;
    error?: object | null;
    message: CitiesApiResponseMessage;
}

