/**
 * Cities Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from './pagination-meta';
import { City } from './city';


export interface CitiesResponseData { 
    /**
     * Cities for the current page
     */
    items: Array<City>;
    pagination: PaginationMeta;
}

