/**
 * Cities Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface City { 
    /**
     * The name of the city
     */
    name: string;
    /**
     * The native name of the city
     */
    name_native: string;
    /**
     * The country where the city is located
     */
    country: string;
    /**
     * The continent where the city is located
     */
    continent: string;
    /**
     * The latitude of the city
     */
    latitude: number;
    /**
     * The longitude of the city
     */
    longitude: number;
    /**
     * The population of the city
     */
    population: number;
    /**
     * The year the city was founded
     */
    founded: number;
    /**
     * Famous landmarks in the city
     */
    landmarks: Array<string>;
}

